
package interfaz;

import dominio.Sistema;


public class MenuPrincipal extends javax.swing.JFrame {

    private Sistema sistema;
    
    public MenuPrincipal(Sistema elSistema) {
        sistema = elSistema;
        initComponents();
        this.setTitle("ERP Empresarial");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        areasMenu = new javax.swing.JMenu();
        jMenuAltaAreas = new javax.swing.JMenuItem();
        jMenuBajaAreas = new javax.swing.JMenuItem();
        jMenuModificacionArea = new javax.swing.JMenuItem();
        jMenuRealizarMovimiento = new javax.swing.JMenuItem();
        managersMenu = new javax.swing.JMenu();
        jMenuAltaManagers = new javax.swing.JMenuItem();
        jMenuBajaManagers = new javax.swing.JMenuItem();
        jMenuModificacionManagers = new javax.swing.JMenuItem();
        empleadosMenu = new javax.swing.JMenu();
        jMenuAltaEmpleados = new javax.swing.JMenuItem();
        reportesMenu = new javax.swing.JMenu();
        jMenuReporteInteligente = new javax.swing.JMenuItem();
        jMenuReporteArea = new javax.swing.JMenu();
        jMenuReporteMovimiento = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        areasMenu.setText("Áreas");

        jMenuAltaAreas.setText("Alta");
        jMenuAltaAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAltaAreasActionPerformed(evt);
            }
        });
        areasMenu.add(jMenuAltaAreas);

        jMenuBajaAreas.setText("Baja");
        jMenuBajaAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBajaAreasActionPerformed(evt);
            }
        });
        areasMenu.add(jMenuBajaAreas);

        jMenuModificacionArea.setText("Modificación");
        jMenuModificacionArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModificacionAreaActionPerformed(evt);
            }
        });
        areasMenu.add(jMenuModificacionArea);

        jMenuRealizarMovimiento.setText("Realizar Movimiento");
        jMenuRealizarMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRealizarMovimientoActionPerformed(evt);
            }
        });
        areasMenu.add(jMenuRealizarMovimiento);

        menuBar.add(areasMenu);

        managersMenu.setText("Managers");

        jMenuAltaManagers.setText("Alta");
        managersMenu.add(jMenuAltaManagers);

        jMenuBajaManagers.setText("Baja");
        jMenuBajaManagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBajaManagersActionPerformed(evt);
            }
        });
        managersMenu.add(jMenuBajaManagers);

        jMenuModificacionManagers.setText("Modificación");
        jMenuModificacionManagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModificacionManagersActionPerformed(evt);
            }
        });
        managersMenu.add(jMenuModificacionManagers);

        menuBar.add(managersMenu);

        empleadosMenu.setText("Empleados");

        jMenuAltaEmpleados.setText("Alta");
        empleadosMenu.add(jMenuAltaEmpleados);

        menuBar.add(empleadosMenu);

        reportesMenu.setText("Reportes");

        jMenuReporteInteligente.setText("Reporte inteligente");
        jMenuReporteInteligente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuReporteInteligenteActionPerformed(evt);
            }
        });
        reportesMenu.add(jMenuReporteInteligente);

        jMenuReporteArea.setText("Reporte de estado de Área");
        reportesMenu.add(jMenuReporteArea);

        jMenuReporteMovimiento.setText("Reporte de Movimiento");
        reportesMenu.add(jMenuReporteMovimiento);

        menuBar.add(reportesMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuRealizarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRealizarMovimientoActionPerformed
        
    }//GEN-LAST:event_jMenuRealizarMovimientoActionPerformed

    private void jMenuAltaAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAltaAreasActionPerformed
        AltaAreas a = new AltaAreas(sistema);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuAltaAreasActionPerformed

    private void jMenuBajaManagersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBajaManagersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBajaManagersActionPerformed

    private void jMenuModificacionManagersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModificacionManagersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuModificacionManagersActionPerformed

    private void jMenuBajaAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBajaAreasActionPerformed
        BajaAreas b = new BajaAreas(sistema);
        b.setVisible(true);
    }//GEN-LAST:event_jMenuBajaAreasActionPerformed

    private void jMenuReporteInteligenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuReporteInteligenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuReporteInteligenteActionPerformed

    private void jMenuModificacionAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModificacionAreaActionPerformed
        ModificacionAreas m = new ModificacionAreas(sistema);
        m.setVisible(true);
    }//GEN-LAST:event_jMenuModificacionAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu areasMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu empleadosMenu;
    private javax.swing.JMenuItem jMenuAltaAreas;
    private javax.swing.JMenuItem jMenuAltaEmpleados;
    private javax.swing.JMenuItem jMenuAltaManagers;
    private javax.swing.JMenuItem jMenuBajaAreas;
    private javax.swing.JMenuItem jMenuBajaManagers;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuModificacionArea;
    private javax.swing.JMenuItem jMenuModificacionManagers;
    private javax.swing.JMenuItem jMenuRealizarMovimiento;
    private javax.swing.JMenu jMenuReporteArea;
    private javax.swing.JMenuItem jMenuReporteInteligente;
    private javax.swing.JMenu jMenuReporteMovimiento;
    private javax.swing.JMenu managersMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu reportesMenu;
    // End of variables declaration//GEN-END:variables

}
