package interfaz;

import dominio.Sistema;
import java.io.BufferedOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;

public class MenuPrincipal extends javax.swing.JFrame {

    private Sistema sistema;

    public MenuPrincipal(Sistema elSistema) {
        sistema = elSistema;
        initComponents();
        this.setTitle("ERP Empresarial");
        this.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt){
                if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_F1){
                    JOptionPane.showMessageDialog(null, "Autores: Santiago Nicolas Alonso Bentancor (349491) y Juan Ignacio Marta Fernández (332281)","Información de Autores",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        });
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                confirmarCierre();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        areasMenu = new javax.swing.JMenu();
        jMenuAltaAreas = new javax.swing.JMenuItem();
        jMenuBajaAreas = new javax.swing.JMenuItem();
        jMenuModificacionArea = new javax.swing.JMenuItem();
        jMenuRealizarMovimiento = new javax.swing.JMenuItem();
        managersMenu = new javax.swing.JMenu();
        jMenuAltaManagers = new javax.swing.JMenuItem();
        jMenuBajaManagers = new javax.swing.JMenuItem();
        jMenuModificacionManagers = new javax.swing.JMenuItem();
        empleadosMenu = new javax.swing.JMenu();
        jMenuAltaEmpleados = new javax.swing.JMenuItem();
        reportesMenu = new javax.swing.JMenu();
        jMenuReporteInteligente = new javax.swing.JMenuItem();
        jMenuItemReporteArea = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema ERP");

        desktopPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        areasMenu.setText("Áreas");

        jMenuAltaAreas.setText("Alta");
        jMenuAltaAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAltaAreasActionPerformed(evt);
            }
        });
        areasMenu.add(jMenuAltaAreas);

        jMenuBajaAreas.setText("Baja");
        jMenuBajaAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBajaAreasActionPerformed(evt);
            }
        });
        areasMenu.add(jMenuBajaAreas);

        jMenuModificacionArea.setText("Modificación");
        jMenuModificacionArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModificacionAreaActionPerformed(evt);
            }
        });
        areasMenu.add(jMenuModificacionArea);

        jMenuRealizarMovimiento.setText("Realizar Movimiento");
        jMenuRealizarMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRealizarMovimientoActionPerformed(evt);
            }
        });
        areasMenu.add(jMenuRealizarMovimiento);

        menuBar.add(areasMenu);

        managersMenu.setText("Managers");

        jMenuAltaManagers.setText("Alta");
        jMenuAltaManagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAltaManagersActionPerformed(evt);
            }
        });
        managersMenu.add(jMenuAltaManagers);

        jMenuBajaManagers.setText("Baja");
        jMenuBajaManagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBajaManagersActionPerformed(evt);
            }
        });
        managersMenu.add(jMenuBajaManagers);

        jMenuModificacionManagers.setText("Modificación");
        jMenuModificacionManagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModificacionManagersActionPerformed(evt);
            }
        });
        managersMenu.add(jMenuModificacionManagers);

        menuBar.add(managersMenu);

        empleadosMenu.setText("Empleados");

        jMenuAltaEmpleados.setText("Alta");
        jMenuAltaEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAltaEmpleadosActionPerformed(evt);
            }
        });
        empleadosMenu.add(jMenuAltaEmpleados);

        menuBar.add(empleadosMenu);

        reportesMenu.setText("Reportes");

        jMenuReporteInteligente.setText("Reporte inteligente");
        jMenuReporteInteligente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuReporteInteligenteActionPerformed(evt);
            }
        });
        reportesMenu.add(jMenuReporteInteligente);

        jMenuItemReporteArea.setText("Reporte de estado de áreas");
        jMenuItemReporteArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReporteAreaActionPerformed(evt);
            }
        });
        reportesMenu.add(jMenuItemReporteArea);

        jMenuItem3.setText("Reporte de Movimiento");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        reportesMenu.add(jMenuItem3);

        menuBar.add(reportesMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuRealizarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRealizarMovimientoActionPerformed
        if (!(sistema.areasOrdenadasPorNombre().size()<2&&sistema.empleadosOrdenadosPorSalario().isEmpty())) {
            MovimientoAreas m = new MovimientoAreas(sistema);
            m.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Para poder realizar un movimiento de áreas deben existir al menos 2 areas y 1 empleado.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jMenuRealizarMovimientoActionPerformed

    private void jMenuAltaAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAltaAreasActionPerformed

        AltaAreas a = new AltaAreas(sistema);
        a.setVisible(true);

    }//GEN-LAST:event_jMenuAltaAreasActionPerformed

    private void jMenuBajaManagersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBajaManagersActionPerformed
        if (!sistema.managersOrdenadosPorAntiguedad().isEmpty()) {
            BajaManagers b = new BajaManagers(sistema);
            b.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Para poder eliminar un manager debe existir al menos 1 mánager.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jMenuBajaManagersActionPerformed

    private void jMenuModificacionManagersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModificacionManagersActionPerformed
        if (!sistema.managersOrdenadosPorAntiguedad().isEmpty()) {
            ModificacionManagers m = new ModificacionManagers(sistema);
            m.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Para poder modificar un manager debe existir al menos 1 mánager.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jMenuModificacionManagersActionPerformed

    private void jMenuBajaAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBajaAreasActionPerformed
        if (!sistema.areasOrdenadasPorNombre().isEmpty()) {
            BajaAreas b = new BajaAreas(sistema);
            b.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Para poder eliminar un área debe existir al menos 1 área.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jMenuBajaAreasActionPerformed

    private void jMenuReporteInteligenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuReporteInteligenteActionPerformed
        if (!(sistema.areasOrdenadasPorNombre().isEmpty() && sistema.managersOrdenadosPorAntiguedad().isEmpty() && sistema.empleadosOrdenadosPorSalario().isEmpty())) {
            ReporteInteligente r = new ReporteInteligente(sistema);
            r.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Para poder hacer un reporte inteligente deben existir al menos 2 areas y 1 empleado.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuReporteInteligenteActionPerformed

    private void jMenuModificacionAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModificacionAreaActionPerformed
        if (!sistema.areasOrdenadasPorNombre().isEmpty()) {
            ModificacionAreas m = new ModificacionAreas(sistema);
            m.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Para poder modificar un área debe existir al menos 1 área.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jMenuModificacionAreaActionPerformed

    private void jMenuAltaEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAltaEmpleadosActionPerformed
        if (!(sistema.areasOrdenadasPorNombre().isEmpty() && sistema.managersOrdenadosPorAntiguedad().isEmpty())) {
            AltaEmpleados a = new AltaEmpleados(sistema);
            a.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Para poder dar de alta a un empleado debe exisitir al menos 1 área y 1 mánager.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jMenuAltaEmpleadosActionPerformed

    private void jMenuAltaManagersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAltaManagersActionPerformed
        AltaManagers a = new AltaManagers(sistema);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuAltaManagersActionPerformed

    private void jMenuItemReporteAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReporteAreaActionPerformed
        if (!sistema.areasOrdenadasPorNombre().isEmpty()) {
            ReporteEstadoAreas r = new ReporteEstadoAreas(sistema);
            r.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Para poder hacer el reporte de área debe existir al menos 1 área.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jMenuItemReporteAreaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (!sistema.getListaMovimientos().isEmpty()) {
            ReporteMovimientos r = new ReporteMovimientos(sistema);
            r.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Para poder hacer el reporte de movimientos debe haberse hecho al menos 1 movimiento.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void confirmarCierre() {
        int opcion = JOptionPane.showConfirmDialog(this, "Desea salir del sistema?", "Salir", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            try {
                FileOutputStream ff = new FileOutputStream("Datos/guardarDatos");
                BufferedOutputStream b = new BufferedOutputStream(ff);
                ObjectOutputStream sss = new ObjectOutputStream(b);
                sss.writeObject(sistema);
                sss.close();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "No se pudieron guardar los datos", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu areasMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu empleadosMenu;
    private javax.swing.JMenuItem jMenuAltaAreas;
    private javax.swing.JMenuItem jMenuAltaEmpleados;
    private javax.swing.JMenuItem jMenuAltaManagers;
    private javax.swing.JMenuItem jMenuBajaAreas;
    private javax.swing.JMenuItem jMenuBajaManagers;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemReporteArea;
    private javax.swing.JMenuItem jMenuModificacionArea;
    private javax.swing.JMenuItem jMenuModificacionManagers;
    private javax.swing.JMenuItem jMenuRealizarMovimiento;
    private javax.swing.JMenuItem jMenuReporteInteligente;
    private javax.swing.JMenu managersMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu reportesMenu;
    // End of variables declaration//GEN-END:variables

}
