/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package interfaz;

/**
 *
 * @author juanm
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setTitle("ERP Empresarial");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        areasMenu = new javax.swing.JMenu();
        openAltaAreas = new javax.swing.JMenuItem();
        openBajaAreas = new javax.swing.JMenuItem();
        openModificacionArea = new javax.swing.JMenuItem();
        openMovimientoAreas = new javax.swing.JMenuItem();
        managersMenu = new javax.swing.JMenu();
        openAltaManagers = new javax.swing.JMenuItem();
        openBajaManagers = new javax.swing.JMenuItem();
        openModificacionManagers = new javax.swing.JMenuItem();
        empleadosMenu = new javax.swing.JMenu();
        openAltaEmpleados = new javax.swing.JMenuItem();
        reportesMenu = new javax.swing.JMenu();
        openReporteInteligente = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        areasMenu.setText("Áreas");

        openAltaAreas.setText("Alta");
        openAltaAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openAltaAreasActionPerformed(evt);
            }
        });
        areasMenu.add(openAltaAreas);

        openBajaAreas.setText("Baja");
        openBajaAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBajaAreasActionPerformed(evt);
            }
        });
        areasMenu.add(openBajaAreas);

        openModificacionArea.setText("Modificación");
        areasMenu.add(openModificacionArea);

        openMovimientoAreas.setText("Realizar movimiento");
        openMovimientoAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMovimientoAreasActionPerformed(evt);
            }
        });
        areasMenu.add(openMovimientoAreas);

        menuBar.add(areasMenu);

        managersMenu.setText("Managers");

        openAltaManagers.setText("Alta");
        managersMenu.add(openAltaManagers);

        openBajaManagers.setText("Baja");
        openBajaManagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBajaManagersActionPerformed(evt);
            }
        });
        managersMenu.add(openBajaManagers);

        openModificacionManagers.setText("Modificación");
        openModificacionManagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openModificacionManagersActionPerformed(evt);
            }
        });
        managersMenu.add(openModificacionManagers);

        menuBar.add(managersMenu);

        empleadosMenu.setText("Empleados");

        openAltaEmpleados.setText("Alta");
        empleadosMenu.add(openAltaEmpleados);

        menuBar.add(empleadosMenu);

        reportesMenu.setText("Reportes");

        openReporteInteligente.setText("Reporte inteligente");
        reportesMenu.add(openReporteInteligente);

        menuBar.add(reportesMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openMovimientoAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMovimientoAreasActionPerformed
        System.exit(0);
    }//GEN-LAST:event_openMovimientoAreasActionPerformed

    private void openAltaAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openAltaAreasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openAltaAreasActionPerformed

    private void openBajaManagersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBajaManagersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openBajaManagersActionPerformed

    private void openModificacionManagersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openModificacionManagersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openModificacionManagersActionPerformed

    private void openBajaAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBajaAreasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openBajaAreasActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu areasMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu empleadosMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu managersMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openAltaAreas;
    private javax.swing.JMenuItem openAltaEmpleados;
    private javax.swing.JMenuItem openAltaManagers;
    private javax.swing.JMenuItem openBajaAreas;
    private javax.swing.JMenuItem openBajaManagers;
    private javax.swing.JMenuItem openModificacionArea;
    private javax.swing.JMenuItem openModificacionManagers;
    private javax.swing.JMenuItem openMovimientoAreas;
    private javax.swing.JMenuItem openReporteInteligente;
    private javax.swing.JMenu reportesMenu;
    // End of variables declaration//GEN-END:variables

}
