
package interfaz;

import dominio.*;
import excepciones.StringVacioException;
import javax.swing.JOptionPane;
import java.util.Observable;
import java.util.Observer;

public class ModificacionAreas extends javax.swing.JFrame implements Observer{
    
    private final Sistema sistema;
    private Area seleccionadaMod;

    public ModificacionAreas(Sistema elSistema) {
        sistema = elSistema;
        initComponents();
        jTextNombre.setEditable(false);
        jTextPresupuesto.setEditable(false);
        this.setTitle("Modifcar Área");
        refrescarPantalla();
        sistema.addObserver(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jListAreasModificacion = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextNombre = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPresupuesto = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextDescripcion = new javax.swing.JTextPane();
        jButtonModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jListAreasModificacion.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListAreasModificacion.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListAreasModificacionValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListAreasModificacion);

        jLabel1.setText("Areas");

        jLabel2.setText("Modificar Descripción");

        jTextNombre.setCaretColor(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(jTextNombre);

        jLabel3.setText("Nombre");

        jLabel4.setText("Descripción");

        jLabel5.setText("Presupuesto Anual");

        jTextPresupuesto.setCaretColor(new java.awt.Color(102, 102, 102));
        jScrollPane3.setViewportView(jTextPresupuesto);

        jScrollPane4.setViewportView(jTextDescripcion);

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButtonModificar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel3)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel4)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonModificar)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed

        try {
            if (seleccionadaMod == null) {
                JOptionPane.showMessageDialog(this, "Error: No se selecciono un area o fue eliminada durante la modificación", "Error", JOptionPane.ERROR_MESSAGE);
                seleccionadaMod = null;
                jTextNombre.setText("");
                jTextDescripcion.setText("");
                jTextPresupuesto.setText("");
            } else {
                seleccionadaMod.setDescripcion(jTextDescripcion.getText());
                JOptionPane.showMessageDialog(this, "Área modificada exitosamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
                jListAreasModificacion.clearSelection();
                refrescarPantalla();
            }
        } catch (StringVacioException e) {
            JOptionPane.showMessageDialog(this, "Error: La descripción no puede estar vacía", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jListAreasModificacionValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListAreasModificacionValueChanged
            
            seleccionadaMod = (Area) jListAreasModificacion.getSelectedValue();
            if (seleccionadaMod == null) {
                jTextNombre.setText("");
                jTextDescripcion.setText("");
                jTextPresupuesto.setText("");
            } else {
            jTextNombre.setText(seleccionadaMod.getNombre());
            jTextDescripcion.setText(seleccionadaMod.getDescripcion());
            jTextPresupuesto.setText("" + seleccionadaMod.getPresupuestoAnual());
            }
    }//GEN-LAST:event_jListAreasModificacionValueChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<Object> jListAreasModificacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextDescripcion;
    private javax.swing.JTextPane jTextNombre;
    private javax.swing.JTextPane jTextPresupuesto;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        refrescarPantalla();
    }
    
    private void refrescarPantalla(){
        jListAreasModificacion.setListData(sistema.areasOrdenadasPorNombre().toArray());
    }
}
