
package interfaz;

import dominio.*;
import javax.swing.JOptionPane;
import java.util.Observable;
import java.util.Observer;

public class MovimientoAreas extends javax.swing.JFrame implements Observer{
    
    private final Sistema sistema;
    private Area origen;
    private Empleado empleado;
    private Area destino;

    public MovimientoAreas(Sistema elSistema) {
        sistema = elSistema;
        initComponents();
        this.setTitle("Movimiento Área");
        refrescarPantalla();
        sistema.addObserver(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jListEmpleadoMover = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListAreaDestino = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListAreaOrigen = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jListMes = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Movimiento de areas");

        jListEmpleadoMover.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jListEmpleadoMover);

        jLabel1.setText("Empleado a Mover");

        jLabel2.setText("Realizar Movimiento");

        jListAreaDestino.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(jListAreaDestino);

        jLabel6.setText("Area de Origen");

        jListAreaOrigen.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListAreaOrigen.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListAreaOrigenValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(jListAreaOrigen);

        jLabel7.setText("Area de Destino");

        jLabel8.setText("Mes del movimiento ");

        jListMes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jListMes);

        jButton1.setText("Realizar Movimiento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel7)
                        .addGap(52, 52, 52)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        empleado = (Empleado) jListEmpleadoMover.getSelectedValue();
        destino = (Area) jListAreaDestino.getSelectedValue();
        if (origen == null) {
            JOptionPane.showMessageDialog(this, "Error: No se selecciono un area de origen o fue eliminada durante la modificación", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (empleado == null) {
            JOptionPane.showMessageDialog(this, "Error: No se selecciono un empleado", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (destino == null) {
            JOptionPane.showMessageDialog(this, "Error: No se selecciono un area de destino o fue eliminada durante la modificación", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (jListMes.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(this, "Error: No se selecciono el mes donde se hará el movimiento", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (origen == destino) {
            JOptionPane.showMessageDialog(this, "Error: El area de origen y destino no pueden ser las mismas", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int mes = jListMes.getSelectedIndex() + 1;
            if(sistema.moverEmpleado(empleado, mes, destino)){
                JOptionPane.showMessageDialog(this, "El empleado se trasladó de área correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
                refrescarPantalla();
            } else {
                JOptionPane.showMessageDialog(this, "Error: El área seleccionada no tiene suficiente presupuesto para este empleado", "Error", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jListAreaOrigenValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListAreaOrigenValueChanged
        origen = (Area) jListAreaOrigen.getSelectedValue();
        if(origen != null){
            jListEmpleadoMover.setListData(origen.getListaEmpleados().toArray());
        }
    }//GEN-LAST:event_jListAreaOrigenValueChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<Object> jListAreaDestino;
    private javax.swing.JList<Object> jListAreaOrigen;
    private javax.swing.JList<Object> jListEmpleadoMover;
    private javax.swing.JList<String> jListMes;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        refrescarPantalla();
    }
    
    private void refrescarPantalla(){
        jListAreaDestino.setListData(sistema.areasOrdenadasPorNombre().toArray());
        jListAreaOrigen.setListData(sistema.areasOrdenadasPorNombre().toArray());
        jListEmpleadoMover.clearSelection();
        jListEmpleadoMover.setListData(new String[0]);
        
    }
}
