// Trabajo desarrollado por: Santiago Alonso 349491 Juan Marta 332281
package interfaz;

import dominio.*;
import excepciones.CedulaInvalidaException;
import excepciones.StringVacioException;
import excepciones.TelefonoInvalidoException;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.JOptionPane;

public class seleccionSistema extends javax.swing.JFrame {

    private Sistema sistema;
    
    public seleccionSistema() {
        initComponents();
        this.setTitle("Comenzar con...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSistemaNuevo = new javax.swing.JButton();
        jButtonSistemaGuardado = new javax.swing.JButton();
        jButtonSistemaDemo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSistemaNuevo.setText("Sistema nuevo");
        jButtonSistemaNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSistemaNuevoActionPerformed(evt);
            }
        });

        jButtonSistemaGuardado.setText("Sistema guardado");
        jButtonSistemaGuardado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSistemaGuardadoActionPerformed(evt);
            }
        });

        jButtonSistemaDemo.setText("Sistema con datos precargados");
        jButtonSistemaDemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSistemaDemoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSistemaNuevo)
                .addGap(18, 18, 18)
                .addComponent(jButtonSistemaGuardado)
                .addGap(18, 18, 18)
                .addComponent(jButtonSistemaDemo)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSistemaNuevo)
                    .addComponent(jButtonSistemaGuardado)
                    .addComponent(jButtonSistemaDemo))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSistemaNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSistemaNuevoActionPerformed
        sistema = new Sistema();
        eliminarcvs();
        CrearVentana(sistema);
    }//GEN-LAST:event_jButtonSistemaNuevoActionPerformed

    private void jButtonSistemaGuardadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSistemaGuardadoActionPerformed
        try {
            FileInputStream ff = new FileInputStream("Datos/guardarDatos");
            BufferedInputStream b = new BufferedInputStream(ff);
            ObjectInputStream sss = new ObjectInputStream(b);
            sistema = (Sistema) sss.readObject();
            sss.close();
            CrearVentana(sistema);
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error: No se ha creado un sistema previamente", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", JOptionPane.ERROR_MESSAGE);
            sistema = new Sistema();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error: no se encontro sistema para leer los datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSistemaGuardadoActionPerformed

    private void jButtonSistemaDemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSistemaDemoActionPerformed
        sistema = new Sistema();
        try {
            sistema.agregarArea(new Area("Personal","Reclutamiento de personal, promociones, gestión de cargos",100000.00));
            sistema.agregarArea(new Area("RRHH","Relacionamiento en la empresa, organigrama, gestión de equipos",80000.00));
            sistema.agregarArea(new Area("Seguridad","Seguridad física, vigilancia, seguridad informática, protocolos y políticas de seguridad",120000.00));
            sistema.agregarArea(new Area("Comunicaciones","Comunicaciones internas, reglas y protocolos, comunicaciones con proveedores y clientes",20000.00));
            sistema.agregarArea(new Area("Marketing","Acciones planificadas, publicidad en medios masivos, publicidad en redes, gestión de redes",95000.00));
            sistema.agregarManager(new Manager("Ana Martínez","45683691","099123456",10));
            sistema.agregarManager(new Manager("Ricardo Morales","32145893","094121212",4));
            sistema.agregarManager(new Manager("Laura Torales","35892575","099654321",1));
            sistema.agregarManager(new Manager("Juan Pablo Zapata","45551977","099202020",5));
            eliminarcvs();
            CrearVentana(sistema);
        } catch (StringVacioException ex) {
            System.getLogger(seleccionSistema.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (CedulaInvalidaException ex) {
            System.getLogger(seleccionSistema.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (TelefonoInvalidoException ex) {
            System.getLogger(seleccionSistema.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        eliminarcvs();
    }//GEN-LAST:event_jButtonSistemaDemoActionPerformed

    private void CrearVentana(Sistema sistema) {
        MenuPrincipal m = new MenuPrincipal(sistema);
        m.setVisible(true);
        this.dispose();
    }
    
    private void eliminarcvs(){
        File carpeta = new File("cvs");
        if(carpeta.exists()){
            File[] listaArchivos = carpeta.listFiles();
            for(int i = 0; i< listaArchivos.length; i++){
                listaArchivos[i].delete();
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSistemaDemo;
    private javax.swing.JButton jButtonSistemaGuardado;
    private javax.swing.JButton jButtonSistemaNuevo;
    // End of variables declaration//GEN-END:variables
}
